# Generated by Django 3.2.6 on 2021-08-23 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apropos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apropos',
            name='description',
        ),
        migrations.RemoveField(
            model_name='apropos',
            name='nom',
        ),
    ]
