# Generated by Django 3.2.6 on 2021-08-23 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apropos', '0002_auto_20210823_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='apropos',
            name='desc',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='apropos',
            name='surnom',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
